### ISSUE TITLE
ToDo:  (initial repo updates)

### ISSUE THREAD

**Issue by E3V3A** [CapstoneReloaded/capstone#1]
Here is a brief unorganized list of things that need immediate attention to be fixed, updated or removed:

---

#### ToDo:

- [x] Add code of conduct document
- [ ] Add an issue template
- [ ] Add a PR template
- [ ] Add a contribution template
- [x] Update the LICENSE file

- [ ] Add a bunch of new issue *Labels*
- [ ] Use wheel python packaging instead of Egg? \
  (see: https://packaging.python.org/discussions/wheel-vs-egg/)

- [ ] **Remove** dead branches
- [ ] **Remove** empty files (mostly unused text files) from root directory
- [ ] Move **all** text documents into `./docs/`, except `README.md`
- [ ] Rename and Update disorganized ChangeLog
- [ ] Remove dead, outdated or unmaintained branches
- [ ] Find developers who are willing to contribute
- [ ] Fix/Update installation instructions 
- [ ] Update Python bindings installation scripts
- [ ] Migrate old but relevant issues from original repo
- [ ] Follow up on unmaintained PR's
- [ ] Make a priority list of things that need fixing ASAP
- [ ] Investigate all the multiple entries in original issue no 1281
- [ ]  
- [ ]  
- [ ]  
- [ ]  
- [ ]  

---

**You know of more things that need to be done?** \
Please add to this issue thread.

**Comment by E3V3A** [comment]
Removed 4 year old TODO file from root.

For your reference it's content was: 
```
Issues to be solved in next versions

[Core]

- X86 can already handle all the malware tricks we are aware of. If you find
  any such instruction sequence that Capstone disassembles wrongly or fails
  completely, please report. Fixing this issue is always the top priority of
  our project.

- More optimization for better performance.

[Bindings]

- OCaml binding is working, but still needs to support the core API better.
```

**Comment by XVilka** [comment]
What about keeping master clean (copy of the original capstone)? Or maybe keeping original master in "original" or something like that? So it will be easier to rebase if something.

**Comment by E3V3A** [comment]
> maybe keeping original master in "original" or something

Yep, that is a good idea. I'll probably reload this entire repo and squash my changes. 
However, I'm still in standby mode, to better understand what is the public interest for this...
